name = "AutoDiffOperators"
uuid = "6e1301d5-4f4d-4fb5-9679-7191e22f0e0e"
version = "0.1.3"

[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
AbstractDifferentiation = "c29ec348-61ec-40c8-8164-b8c60e9d9f3d"
AffineMaps = "2c83c9a8-abf5-4329-a0d7-deffaf474661"
FunctionChains = "8e6b2b91-af83-483e-ba35-d00930e4cf9b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[weakdeps]
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[extensions]
AutoDiffOperatorsEnzymeExt = "Enzyme"
AutoDiffOperatorsFiniteDifferencesExt = "FiniteDifferences"
AutoDiffOperatorsForwardDiffExt = "ForwardDiff"
AutoDiffOperatorsLinearMapsExt = "LinearMaps"
AutoDiffOperatorsZygoteExt = "Zygote"

[compat]
ADTypes = "0.1"
AbstractDifferentiation = "0.5"
AffineMaps = "0.2"
Enzyme = "0.11"
FiniteDifferences = "0.12"
ForwardDiff = "0.10"
FunctionChains = "0.1"
LinearMaps = "3"
Requires = "1"
Zygote = "0.6"
julia = "1.6"

[extras]
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
